// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type InitializeRequest struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitializeRequest) Reset()         { *m = InitializeRequest{} }
func (m *InitializeRequest) String() string { return proto.CompactTextString(m) }
func (*InitializeRequest) ProtoMessage()    {}
func (*InitializeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_f4e8fbd2e384972a, []int{0}
}
func (m *InitializeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitializeRequest.Unmarshal(m, b)
}
func (m *InitializeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitializeRequest.Marshal(b, m, deterministic)
}
func (dst *InitializeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitializeRequest.Merge(dst, src)
}
func (m *InitializeRequest) XXX_Size() int {
	return xxx_messageInfo_InitializeRequest.Size(m)
}
func (m *InitializeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InitializeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InitializeRequest proto.InternalMessageInfo

func (m *InitializeRequest) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

type InitializeResponse struct {
	Proof                *Proof   `protobuf:"bytes,1,opt,name=proof,proto3" json:"proof,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitializeResponse) Reset()         { *m = InitializeResponse{} }
func (m *InitializeResponse) String() string { return proto.CompactTextString(m) }
func (*InitializeResponse) ProtoMessage()    {}
func (*InitializeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_f4e8fbd2e384972a, []int{1}
}
func (m *InitializeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitializeResponse.Unmarshal(m, b)
}
func (m *InitializeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitializeResponse.Marshal(b, m, deterministic)
}
func (dst *InitializeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitializeResponse.Merge(dst, src)
}
func (m *InitializeResponse) XXX_Size() int {
	return xxx_messageInfo_InitializeResponse.Size(m)
}
func (m *InitializeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InitializeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InitializeResponse proto.InternalMessageInfo

func (m *InitializeResponse) GetProof() *Proof {
	if m != nil {
		return m.Proof
	}
	return nil
}

type ExecuteRequest struct {
	Challenge            []byte   `protobuf:"bytes,1,opt,name=challenge,proto3" json:"challenge,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecuteRequest) Reset()         { *m = ExecuteRequest{} }
func (m *ExecuteRequest) String() string { return proto.CompactTextString(m) }
func (*ExecuteRequest) ProtoMessage()    {}
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_f4e8fbd2e384972a, []int{2}
}
func (m *ExecuteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteRequest.Unmarshal(m, b)
}
func (m *ExecuteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteRequest.Marshal(b, m, deterministic)
}
func (dst *ExecuteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteRequest.Merge(dst, src)
}
func (m *ExecuteRequest) XXX_Size() int {
	return xxx_messageInfo_ExecuteRequest.Size(m)
}
func (m *ExecuteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteRequest proto.InternalMessageInfo

func (m *ExecuteRequest) GetChallenge() []byte {
	if m != nil {
		return m.Challenge
	}
	return nil
}

type ExecuteResponse struct {
	Proof                *Proof   `protobuf:"bytes,1,opt,name=proof,proto3" json:"proof,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecuteResponse) Reset()         { *m = ExecuteResponse{} }
func (m *ExecuteResponse) String() string { return proto.CompactTextString(m) }
func (*ExecuteResponse) ProtoMessage()    {}
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_f4e8fbd2e384972a, []int{3}
}
func (m *ExecuteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteResponse.Unmarshal(m, b)
}
func (m *ExecuteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteResponse.Marshal(b, m, deterministic)
}
func (dst *ExecuteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteResponse.Merge(dst, src)
}
func (m *ExecuteResponse) XXX_Size() int {
	return xxx_messageInfo_ExecuteResponse.Size(m)
}
func (m *ExecuteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteResponse proto.InternalMessageInfo

func (m *ExecuteResponse) GetProof() *Proof {
	if m != nil {
		return m.Proof
	}
	return nil
}

type GetProofRequest struct {
	Challenge            []byte   `protobuf:"bytes,1,opt,name=challenge,proto3" json:"challenge,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProofRequest) Reset()         { *m = GetProofRequest{} }
func (m *GetProofRequest) String() string { return proto.CompactTextString(m) }
func (*GetProofRequest) ProtoMessage()    {}
func (*GetProofRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_f4e8fbd2e384972a, []int{4}
}
func (m *GetProofRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProofRequest.Unmarshal(m, b)
}
func (m *GetProofRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProofRequest.Marshal(b, m, deterministic)
}
func (dst *GetProofRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProofRequest.Merge(dst, src)
}
func (m *GetProofRequest) XXX_Size() int {
	return xxx_messageInfo_GetProofRequest.Size(m)
}
func (m *GetProofRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProofRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProofRequest proto.InternalMessageInfo

func (m *GetProofRequest) GetChallenge() []byte {
	if m != nil {
		return m.Challenge
	}
	return nil
}

type GetProofResponse struct {
	Proof                *Proof   `protobuf:"bytes,1,opt,name=proof,proto3" json:"proof,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProofResponse) Reset()         { *m = GetProofResponse{} }
func (m *GetProofResponse) String() string { return proto.CompactTextString(m) }
func (*GetProofResponse) ProtoMessage()    {}
func (*GetProofResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_f4e8fbd2e384972a, []int{5}
}
func (m *GetProofResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProofResponse.Unmarshal(m, b)
}
func (m *GetProofResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProofResponse.Marshal(b, m, deterministic)
}
func (dst *GetProofResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProofResponse.Merge(dst, src)
}
func (m *GetProofResponse) XXX_Size() int {
	return xxx_messageInfo_GetProofResponse.Size(m)
}
func (m *GetProofResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProofResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetProofResponse proto.InternalMessageInfo

func (m *GetProofResponse) GetProof() *Proof {
	if m != nil {
		return m.Proof
	}
	return nil
}

type ResetRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetRequest) Reset()         { *m = ResetRequest{} }
func (m *ResetRequest) String() string { return proto.CompactTextString(m) }
func (*ResetRequest) ProtoMessage()    {}
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_f4e8fbd2e384972a, []int{6}
}
func (m *ResetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetRequest.Unmarshal(m, b)
}
func (m *ResetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetRequest.Marshal(b, m, deterministic)
}
func (dst *ResetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetRequest.Merge(dst, src)
}
func (m *ResetRequest) XXX_Size() int {
	return xxx_messageInfo_ResetRequest.Size(m)
}
func (m *ResetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResetRequest proto.InternalMessageInfo

type ResetResponse struct {
	DeletedDir           string   `protobuf:"bytes,1,opt,name=deletedDir,json=deleted_dir,proto3" json:"deletedDir,omitempty"`
	NumOfDeletedFiles    int32    `protobuf:"varint,2,opt,name=numOfDeletedFiles,json=num_of_deleted_files,proto3" json:"numOfDeletedFiles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetResponse) Reset()         { *m = ResetResponse{} }
func (m *ResetResponse) String() string { return proto.CompactTextString(m) }
func (*ResetResponse) ProtoMessage()    {}
func (*ResetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_f4e8fbd2e384972a, []int{7}
}
func (m *ResetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetResponse.Unmarshal(m, b)
}
func (m *ResetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetResponse.Marshal(b, m, deterministic)
}
func (dst *ResetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetResponse.Merge(dst, src)
}
func (m *ResetResponse) XXX_Size() int {
	return xxx_messageInfo_ResetResponse.Size(m)
}
func (m *ResetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResetResponse proto.InternalMessageInfo

func (m *ResetResponse) GetDeletedDir() string {
	if m != nil {
		return m.DeletedDir
	}
	return ""
}

func (m *ResetResponse) GetNumOfDeletedFiles() int32 {
	if m != nil {
		return m.NumOfDeletedFiles
	}
	return 0
}

type GetInfoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInfoRequest) Reset()         { *m = GetInfoRequest{} }
func (m *GetInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetInfoRequest) ProtoMessage()    {}
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_f4e8fbd2e384972a, []int{8}
}
func (m *GetInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfoRequest.Unmarshal(m, b)
}
func (m *GetInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfoRequest.Marshal(b, m, deterministic)
}
func (dst *GetInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfoRequest.Merge(dst, src)
}
func (m *GetInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetInfoRequest.Size(m)
}
func (m *GetInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfoRequest proto.InternalMessageInfo

type GetInfoResponse struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Params               *Params  `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	State                *State   `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInfoResponse) Reset()         { *m = GetInfoResponse{} }
func (m *GetInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetInfoResponse) ProtoMessage()    {}
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_f4e8fbd2e384972a, []int{9}
}
func (m *GetInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfoResponse.Unmarshal(m, b)
}
func (m *GetInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfoResponse.Marshal(b, m, deterministic)
}
func (dst *GetInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfoResponse.Merge(dst, src)
}
func (m *GetInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetInfoResponse.Size(m)
}
func (m *GetInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfoResponse proto.InternalMessageInfo

func (m *GetInfoResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *GetInfoResponse) GetParams() *Params {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *GetInfoResponse) GetState() *State {
	if m != nil {
		return m.State
	}
	return nil
}

type ShutdownRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShutdownRequest) Reset()         { *m = ShutdownRequest{} }
func (m *ShutdownRequest) String() string { return proto.CompactTextString(m) }
func (*ShutdownRequest) ProtoMessage()    {}
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_f4e8fbd2e384972a, []int{10}
}
func (m *ShutdownRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShutdownRequest.Unmarshal(m, b)
}
func (m *ShutdownRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShutdownRequest.Marshal(b, m, deterministic)
}
func (dst *ShutdownRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShutdownRequest.Merge(dst, src)
}
func (m *ShutdownRequest) XXX_Size() int {
	return xxx_messageInfo_ShutdownRequest.Size(m)
}
func (m *ShutdownRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShutdownRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShutdownRequest proto.InternalMessageInfo

type ShutdownResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShutdownResponse) Reset()         { *m = ShutdownResponse{} }
func (m *ShutdownResponse) String() string { return proto.CompactTextString(m) }
func (*ShutdownResponse) ProtoMessage()    {}
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_f4e8fbd2e384972a, []int{11}
}
func (m *ShutdownResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShutdownResponse.Unmarshal(m, b)
}
func (m *ShutdownResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShutdownResponse.Marshal(b, m, deterministic)
}
func (dst *ShutdownResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShutdownResponse.Merge(dst, src)
}
func (m *ShutdownResponse) XXX_Size() int {
	return xxx_messageInfo_ShutdownResponse.Size(m)
}
func (m *ShutdownResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ShutdownResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ShutdownResponse proto.InternalMessageInfo

type Proof struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Challenge            []byte   `protobuf:"bytes,2,opt,name=challenge,proto3" json:"challenge,omitempty"`
	MerkleRoot           []byte   `protobuf:"bytes,3,opt,name=merkleRoot,json=merkle_root,proto3" json:"merkleRoot,omitempty"`
	ProvenLeaves         [][]byte `protobuf:"bytes,4,rep,name=provenLeaves,json=proven_leaves,proto3" json:"provenLeaves,omitempty"`
	ProofNodes           [][]byte `protobuf:"bytes,5,rep,name=proofNodes,json=proof_nodes,proto3" json:"proofNodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Proof) Reset()         { *m = Proof{} }
func (m *Proof) String() string { return proto.CompactTextString(m) }
func (*Proof) ProtoMessage()    {}
func (*Proof) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_f4e8fbd2e384972a, []int{12}
}
func (m *Proof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Proof.Unmarshal(m, b)
}
func (m *Proof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Proof.Marshal(b, m, deterministic)
}
func (dst *Proof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Proof.Merge(dst, src)
}
func (m *Proof) XXX_Size() int {
	return xxx_messageInfo_Proof.Size(m)
}
func (m *Proof) XXX_DiscardUnknown() {
	xxx_messageInfo_Proof.DiscardUnknown(m)
}

var xxx_messageInfo_Proof proto.InternalMessageInfo

func (m *Proof) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Proof) GetChallenge() []byte {
	if m != nil {
		return m.Challenge
	}
	return nil
}

func (m *Proof) GetMerkleRoot() []byte {
	if m != nil {
		return m.MerkleRoot
	}
	return nil
}

func (m *Proof) GetProvenLeaves() [][]byte {
	if m != nil {
		return m.ProvenLeaves
	}
	return nil
}

func (m *Proof) GetProofNodes() [][]byte {
	if m != nil {
		return m.ProofNodes
	}
	return nil
}

type Params struct {
	SpacePerUnit         int64    `protobuf:"varint,1,opt,name=spacePerUnit,json=space_per_unit,proto3" json:"spacePerUnit,omitempty"`
	Difficulty           int32    `protobuf:"varint,2,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	T                    int32    `protobuf:"varint,3,opt,name=t,proto3" json:"t,omitempty"`
	CacheLayer           int32    `protobuf:"varint,4,opt,name=cacheLayer,json=cache_layer,proto3" json:"cacheLayer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_f4e8fbd2e384972a, []int{13}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Params.Unmarshal(m, b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Params.Marshal(b, m, deterministic)
}
func (dst *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(dst, src)
}
func (m *Params) XXX_Size() int {
	return xxx_messageInfo_Params.Size(m)
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetSpacePerUnit() int64 {
	if m != nil {
		return m.SpacePerUnit
	}
	return 0
}

func (m *Params) GetDifficulty() int32 {
	if m != nil {
		return m.Difficulty
	}
	return 0
}

func (m *Params) GetT() int32 {
	if m != nil {
		return m.T
	}
	return 0
}

func (m *Params) GetCacheLayer() int32 {
	if m != nil {
		return m.CacheLayer
	}
	return 0
}

type State struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Dir                  string   `protobuf:"bytes,3,opt,name=dir,proto3" json:"dir,omitempty"`
	ProvenChallenges     []string `protobuf:"bytes,2,rep,name=provenChallenges,json=proven_challenges,proto3" json:"provenChallenges,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *State) Reset()         { *m = State{} }
func (m *State) String() string { return proto.CompactTextString(m) }
func (*State) ProtoMessage()    {}
func (*State) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_f4e8fbd2e384972a, []int{14}
}
func (m *State) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_State.Unmarshal(m, b)
}
func (m *State) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_State.Marshal(b, m, deterministic)
}
func (dst *State) XXX_Merge(src proto.Message) {
	xxx_messageInfo_State.Merge(dst, src)
}
func (m *State) XXX_Size() int {
	return xxx_messageInfo_State.Size(m)
}
func (m *State) XXX_DiscardUnknown() {
	xxx_messageInfo_State.DiscardUnknown(m)
}

var xxx_messageInfo_State proto.InternalMessageInfo

func (m *State) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *State) GetDir() string {
	if m != nil {
		return m.Dir
	}
	return ""
}

func (m *State) GetProvenChallenges() []string {
	if m != nil {
		return m.ProvenChallenges
	}
	return nil
}

func init() {
	proto.RegisterType((*InitializeRequest)(nil), "api.InitializeRequest")
	proto.RegisterType((*InitializeResponse)(nil), "api.InitializeResponse")
	proto.RegisterType((*ExecuteRequest)(nil), "api.ExecuteRequest")
	proto.RegisterType((*ExecuteResponse)(nil), "api.ExecuteResponse")
	proto.RegisterType((*GetProofRequest)(nil), "api.GetProofRequest")
	proto.RegisterType((*GetProofResponse)(nil), "api.GetProofResponse")
	proto.RegisterType((*ResetRequest)(nil), "api.ResetRequest")
	proto.RegisterType((*ResetResponse)(nil), "api.ResetResponse")
	proto.RegisterType((*GetInfoRequest)(nil), "api.GetInfoRequest")
	proto.RegisterType((*GetInfoResponse)(nil), "api.GetInfoResponse")
	proto.RegisterType((*ShutdownRequest)(nil), "api.ShutdownRequest")
	proto.RegisterType((*ShutdownResponse)(nil), "api.ShutdownResponse")
	proto.RegisterType((*Proof)(nil), "api.Proof")
	proto.RegisterType((*Params)(nil), "api.Params")
	proto.RegisterType((*State)(nil), "api.State")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PostClient is the client API for Post service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PostClient interface {
	Initialize(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (*InitializeResponse, error)
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
	GetProof(ctx context.Context, in *GetProofRequest, opts ...grpc.CallOption) (*GetProofResponse, error)
	Reset(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*ResetResponse, error)
	GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error)
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error)
}

type postClient struct {
	cc *grpc.ClientConn
}

func NewPostClient(cc *grpc.ClientConn) PostClient {
	return &postClient{cc}
}

func (c *postClient) Initialize(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (*InitializeResponse, error) {
	out := new(InitializeResponse)
	err := c.cc.Invoke(ctx, "/api.Post/Initialize", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	out := new(ExecuteResponse)
	err := c.cc.Invoke(ctx, "/api.Post/Execute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postClient) GetProof(ctx context.Context, in *GetProofRequest, opts ...grpc.CallOption) (*GetProofResponse, error) {
	out := new(GetProofResponse)
	err := c.cc.Invoke(ctx, "/api.Post/GetProof", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postClient) Reset(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*ResetResponse, error) {
	out := new(ResetResponse)
	err := c.cc.Invoke(ctx, "/api.Post/Reset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postClient) GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error) {
	out := new(GetInfoResponse)
	err := c.cc.Invoke(ctx, "/api.Post/GetInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error) {
	out := new(ShutdownResponse)
	err := c.cc.Invoke(ctx, "/api.Post/Shutdown", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostServer is the server API for Post service.
type PostServer interface {
	Initialize(context.Context, *InitializeRequest) (*InitializeResponse, error)
	Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
	GetProof(context.Context, *GetProofRequest) (*GetProofResponse, error)
	Reset(context.Context, *ResetRequest) (*ResetResponse, error)
	GetInfo(context.Context, *GetInfoRequest) (*GetInfoResponse, error)
	Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error)
}

func RegisterPostServer(s *grpc.Server, srv PostServer) {
	s.RegisterService(&_Post_serviceDesc, srv)
}

func _Post_Initialize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitializeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServer).Initialize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Post/Initialize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServer).Initialize(ctx, req.(*InitializeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Post_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Post/Execute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServer).Execute(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Post_GetProof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProofRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServer).GetProof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Post/GetProof",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServer).GetProof(ctx, req.(*GetProofRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Post_Reset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServer).Reset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Post/Reset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServer).Reset(ctx, req.(*ResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Post_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Post/GetInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServer).GetInfo(ctx, req.(*GetInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Post_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Post/Shutdown",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Post_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Post",
	HandlerType: (*PostServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Initialize",
			Handler:    _Post_Initialize_Handler,
		},
		{
			MethodName: "Execute",
			Handler:    _Post_Execute_Handler,
		},
		{
			MethodName: "GetProof",
			Handler:    _Post_GetProof_Handler,
		},
		{
			MethodName: "Reset",
			Handler:    _Post_Reset_Handler,
		},
		{
			MethodName: "GetInfo",
			Handler:    _Post_GetInfo_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _Post_Shutdown_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_api_f4e8fbd2e384972a) }

var fileDescriptor_api_f4e8fbd2e384972a = []byte{
	// 691 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0x4d, 0x6f, 0x13, 0x3f,
	0x10, 0xc6, 0x95, 0xa4, 0x69, 0x9b, 0xd9, 0x6d, 0x9a, 0xb8, 0xf9, 0xf7, 0x1f, 0xa2, 0x0a, 0xa2,
	0x2d, 0x87, 0x08, 0xa4, 0x46, 0xb4, 0x88, 0x03, 0x37, 0x44, 0x69, 0x55, 0xa9, 0xd0, 0xca, 0x15,
	0x88, 0xdb, 0xca, 0x64, 0x67, 0x5b, 0x8b, 0x8d, 0xbd, 0x78, 0x9d, 0x40, 0x91, 0xb8, 0xf0, 0x15,
	0xb8, 0xf2, 0xad, 0x38, 0x71, 0xe7, 0x83, 0x20, 0xbf, 0xe4, 0xfd, 0x40, 0x6f, 0xdd, 0xdf, 0xd8,
	0xcf, 0xe3, 0x99, 0xe9, 0x13, 0xa8, 0xb1, 0x9c, 0x1f, 0xe4, 0x4a, 0x6a, 0x49, 0x2a, 0x2c, 0xe7,
	0x9d, 0xbd, 0x6b, 0x29, 0xaf, 0x33, 0xec, 0xb3, 0x9c, 0xf7, 0x99, 0x10, 0x52, 0x33, 0xcd, 0xa5,
	0x28, 0xdc, 0x91, 0x68, 0x1f, 0x9a, 0x67, 0x82, 0x6b, 0xce, 0x32, 0xfe, 0x15, 0x29, 0x7e, 0x1a,
	0x61, 0xa1, 0x49, 0x1d, 0xca, 0x3c, 0x69, 0x97, 0xba, 0xa5, 0x5e, 0x48, 0xcb, 0x3c, 0x89, 0x9e,
	0x01, 0x99, 0x3f, 0x54, 0xe4, 0x52, 0x14, 0x48, 0xba, 0x50, 0xcd, 0x95, 0x94, 0xa9, 0x3d, 0x18,
	0x1c, 0xc2, 0x81, 0x31, 0xbe, 0x34, 0x84, 0xba, 0x42, 0x74, 0x00, 0xf5, 0x57, 0x5f, 0x70, 0x30,
	0xd2, 0x53, 0xe5, 0x3d, 0xa8, 0x0d, 0x6e, 0x58, 0x96, 0xa1, 0xb8, 0x46, 0x6f, 0x30, 0x03, 0xd1,
	0x11, 0x6c, 0x4f, 0xcf, 0xdf, 0xd9, 0xa4, 0x0f, 0xdb, 0xa7, 0xa8, 0x1d, 0xba, 0x93, 0xcb, 0x53,
	0x68, 0xcc, 0x2e, 0xdc, 0xd9, 0xa6, 0x0e, 0x21, 0xc5, 0x02, 0xb5, 0xf7, 0x88, 0x18, 0x6c, 0xf9,
	0x6f, 0x2f, 0xf1, 0x00, 0x20, 0xc1, 0x0c, 0x35, 0x26, 0xc7, 0x5c, 0x59, 0x9d, 0x1a, 0x0d, 0x3c,
	0x89, 0x13, 0xae, 0x48, 0x1f, 0x9a, 0x62, 0x34, 0xbc, 0x48, 0x8f, 0x1d, 0x3b, 0xe1, 0x19, 0x16,
	0xed, 0x72, 0xb7, 0xd4, 0xab, 0xd2, 0x96, 0x18, 0x0d, 0x63, 0x99, 0xc6, 0x93, 0xe3, 0xa9, 0xa9,
	0x45, 0x0d, 0xa8, 0x9f, 0xa2, 0x3e, 0x13, 0xa9, 0x9c, 0x98, 0x2a, 0xdb, 0xab, 0x23, 0xde, 0xb6,
	0x0d, 0x1b, 0x63, 0x54, 0x05, 0x97, 0xc2, 0x7b, 0x4e, 0x3e, 0xc9, 0x3e, 0xac, 0xe7, 0x4c, 0xb1,
	0xa1, 0x33, 0x09, 0x0e, 0x03, 0xd7, 0x94, 0x45, 0xd4, 0x97, 0x4c, 0xe3, 0x85, 0x66, 0x1a, 0xdb,
	0x95, 0xb9, 0xc6, 0xaf, 0x0c, 0xa1, 0xae, 0x10, 0x35, 0x61, 0xfb, 0xea, 0x66, 0xa4, 0x13, 0xf9,
	0x59, 0x4c, 0x9e, 0x41, 0xa0, 0x31, 0x43, 0xee, 0x1d, 0xd1, 0xcf, 0x12, 0x54, 0xed, 0xc0, 0x96,
	0xff, 0x7b, 0x16, 0xb7, 0x51, 0x5e, 0xda, 0x86, 0x19, 0xdb, 0x10, 0xd5, 0xc7, 0x0c, 0xa9, 0x94,
	0xda, 0xbe, 0x22, 0xa4, 0x81, 0x23, 0xb1, 0x92, 0x52, 0x93, 0x7d, 0x08, 0x73, 0x25, 0xc7, 0x28,
	0xce, 0x91, 0x8d, 0xb1, 0x68, 0xaf, 0x75, 0x2b, 0xbd, 0x90, 0x6e, 0x39, 0x16, 0x67, 0x16, 0x1a,
	0x15, 0xbb, 0xa6, 0x37, 0x32, 0xc1, 0xa2, 0x5d, 0xb5, 0x47, 0x02, 0x4b, 0x62, 0x61, 0x50, 0xf4,
	0x0d, 0xd6, 0x5d, 0xe7, 0xe4, 0x21, 0x84, 0x45, 0xce, 0x06, 0x78, 0x89, 0xea, 0xad, 0xe0, 0xda,
	0x3e, 0xb4, 0x42, 0xeb, 0x96, 0xc5, 0x39, 0xaa, 0x78, 0x24, 0xb8, 0x26, 0xf7, 0x01, 0x12, 0x9e,
	0xa6, 0x7c, 0x30, 0xca, 0xf4, 0xad, 0xdf, 0xd2, 0x1c, 0x21, 0x21, 0x94, 0xdc, 0x6b, 0xab, 0xb4,
	0xa4, 0x8d, 0xfd, 0x80, 0x0d, 0x6e, 0xf0, 0x9c, 0xdd, 0xa2, 0x6a, 0xaf, 0x59, 0x1c, 0x58, 0x12,
	0x67, 0x06, 0x45, 0xef, 0xa0, 0x6a, 0x87, 0xba, 0x32, 0x9c, 0x06, 0x54, 0x12, 0xae, 0xac, 0x52,
	0x8d, 0x9a, 0x3f, 0xc9, 0x63, 0x68, 0xb8, 0xde, 0x5e, 0x4e, 0x66, 0x64, 0x16, 0x58, 0xe9, 0xd5,
	0x68, 0xd3, 0xf7, 0x3c, 0x1d, 0x5e, 0x71, 0xf8, 0xbb, 0x02, 0x6b, 0x97, 0xb2, 0xd0, 0xe4, 0x3d,
	0xc0, 0x2c, 0xa2, 0x64, 0xd7, 0xae, 0x71, 0x25, 0xd8, 0x9d, 0xff, 0x57, 0xb8, 0xdf, 0xde, 0xbd,
	0xef, 0xbf, 0xfe, 0xfc, 0x28, 0xef, 0x44, 0xf5, 0xfe, 0xf8, 0x49, 0x9f, 0x4f, 0xeb, 0xcf, 0x4b,
	0x8f, 0xc8, 0x39, 0x6c, 0xf8, 0x50, 0x92, 0x1d, 0x7b, 0x7d, 0x31, 0xd2, 0x9d, 0xd6, 0x22, 0xf4,
	0x82, 0xbb, 0x56, 0xb0, 0x11, 0x05, 0x46, 0x10, 0x5d, 0xd1, 0xa8, 0x5d, 0xc0, 0xe6, 0x24, 0x7c,
	0xc4, 0xdd, 0x5c, 0x0a, 0x6f, 0xe7, 0xbf, 0x25, 0xfa, 0x0f, 0xc1, 0x17, 0x50, 0xb5, 0x39, 0x24,
	0x4d, 0x7b, 0x6f, 0x3e, 0xa3, 0x1d, 0x32, 0x8f, 0xbc, 0x4e, 0xd3, 0xea, 0x04, 0x51, 0xcd, 0xe8,
	0x28, 0x7b, 0xf3, 0x04, 0x36, 0x7c, 0xaa, 0x7c, 0x87, 0x8b, 0xa9, 0xeb, 0xb4, 0x16, 0xa1, 0x17,
	0x6a, 0x58, 0x21, 0x20, 0x9b, 0x6e, 0x64, 0xa9, 0x24, 0xaf, 0x61, 0x73, 0x12, 0x0b, 0xdf, 0xdb,
	0x52, 0x70, 0x7c, 0x6f, 0x2b, 0xd9, 0x69, 0x59, 0xa9, 0x7a, 0x14, 0x1a, 0xa9, 0xc2, 0x57, 0x3f,
	0xac, 0xdb, 0x5f, 0xe8, 0xa3, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x36, 0xb0, 0xae, 0xf5, 0xd1,
	0x05, 0x00, 0x00,
}
