// Code generated by github.com/spacemeshos/go-scale/scalegen. DO NOT EDIT.

package shared

import (
	"github.com/spacemeshos/go-scale"
)

func (t *Proof) EncodeScale(enc *scale.Encoder) (total int, err error) {
	if n, err := scale.EncodeCompact32(enc, uint32(t.Nonce)); err != nil {
		return total, err
	} else {
		total += n
	}
	if n, err := scale.EncodeByteSlice(enc, t.Indices); err != nil {
		return total, err
	} else {
		total += n
	}
	return total, nil
}

func (t *Proof) DecodeScale(dec *scale.Decoder) (total int, err error) {
	if field, n, err := scale.DecodeCompact32(dec); err != nil {
		return total, err
	} else {
		total += n
		t.Nonce = uint32(field)
	}
	if field, n, err := scale.DecodeByteSlice(dec); err != nil {
		return total, err
	} else {
		total += n
		t.Indices = field
	}
	return total, nil
}
